export const posText = {
  top: {
    connectionOnline: "Bağlantı Aktif",
    connectionOffline: "Bağlantı Kesik",
    activeSale: "Aktif Satış",
    cashier: "Kasiyer",
    branch: "Şube",
    register: "Kasa",
    customer: "Müşteri",
    currency: "Para Birimi",
  },
  actions: {
    fastSale: "Hızlı Satış",
    barcodeScan: "Barkod Oku",
    productSearch: "Ürün Ara",
    customerSelect: "Müşteri Seç",
    suspend: "Beklemeye Al",
    suspendedSales: "Bekleyen Satışlar",
    returnMode: "İade Modu",
    priceCheck: "Fiyat Gör",
    printReceipt: "Fiş Yazdır",
    clearCart: "Satış İptal",
    completeSale: "Satışı Tamamla",
    mixedPayment: "Karma Ödeme",
  },
  totals: {
    subtotal: "Ara Toplam",
    vat: "KDV Toplamı",
    collected: "Tahsil Edilen",
    remaining: "Kalan",
    change: "Para Üstü",
    total: "Toplam Tutar",
  },
} as const;
